### ISSUE TITLE
Account endpoint is no longer documented

### ISSUE THREAD

**Issue by mjsqu** [MeltanoLabs/tap-dbt#176]
```
Cannot start plugin tap-dbt: Catalog discovery failed
...
KeyError: 'Account'
...
jsonschema.exceptions.RefResolutionError: Unresolvable JSON pointer: 'components/schemas/Account'
```

May be caused by changes to the open api spec recently: https://github.com/dbt-labs/dbt-cloud-openapi-spec/commit/b88cc2120ba26bb802e6fba6f76faa1bc099469c

**Comment by mjsqu** [comment]
The `components/schemas/Account` path was replaced by:

```yaml
components:
  schemas:
    AccountAzureActiveDirectoryApplication:
    AccountAzureActiveDirectoryApplicationRequest:
    AccountGitlabApplication:
    AccountGitlabApplicationRequest:
```
