### ISSUE TITLE
Declare more fields as nullable

### ISSUE THREAD

**Issue by edgarrmondragon** [MeltanoLabs/tap-dbt#212]
From a Slack conversation:

<blockquote>

Trying to run [tap-dbt](https://hub.meltano.com/extractors/tap-dbt/) and I'm running into some issues that I think would apply more generally to other taps too, but I couldn't find an answer in the forums or slack:

1. Allowing NULL types globally: The expected schema for most of the fields in tap-dbt does not allow NULL values. For example in the runs stream, the field dbt_version is configured to expect a type of string like:

```
          "dbt_version": {
            "type": "string"
          }
```

</blockquote>

The solution would involve one of two alternatives:

* Manually add the "null" type [in all the schemas](https://github.com/MeltanoLabs/tap-dbt/tree/abc60b5c6a78ab8b45a3f3a17a4433da28d224c9/tap_dbt/schemas)
* Refactor the schemas to use the [SDK typing helpers](https://sdk.meltano.com/en/latest/typing.html), which make fields nullable by default.

---

* [Slack](https://meltano.slack.com/archives/C01TCRBBJD7/p1694206154802229?thread_ts=1694018049.841059&cid=C01TCRBBJD7)
* [discuss.meltano.com](https://discuss.meltano.com/t/15641321/trying-to-run-https-hub-meltano-com-extractors-tap-dbt-tap-d#8ac04122-d478-4b57-99a3-6403ffc1e27e)

**Comment by mjsqu** [comment]
I think the schema is being derived from the content retrieved from: `tap_dbt.client.OPENAPI_URL`. For example the following block is retrieved for the `Jobs` endpoint:

```yml
    Job:
      type: "object"
      required:
        - id
        - account_id
        - project_id
        - environment_id
        - dbt_version
        - name
        - execute_steps
        - state
        - triggers
        - settings
        - schedule
      properties:
        id:
          type: integer
          nullable: true
          description: Must be `null` when creating a new Job
...
        dbt_version:
          type: string
          nullable: true
          description: Overrides the dbt_version specified on the attached Environment if provided
          example: 0.17.1
```

Whereas the extracted schema is:

```json
      "schema": {
        "properties": {
          "id": {
            "description": "Must be `null` when creating a new Job",
            "type": "integer"
          },
...
          "dbt_version": {
            "description": "Overrides the dbt_version specified on the attached Environment if provided",
            "type": "string"
          }
```

`nullable` does not appear to be carried over when converting the yaml to the json schema.
